insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('218634182-4', 'cubilia curae duis', 'Allard Swinbourne', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('119466043-6', 'ipsum primis in faucibus', 'Artur Klemz', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('801293439-6', 'at ipsum ac tellus', 'Gordan Howles', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('030589807-8', 'faucibus orci luctus', 'Jori Renshaw', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('573661441-3', 'pellentesque volutpat', 'Cinnamon Ibarra', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('119455807-0', 'odio justo sollicitudin ut suscipit', 'Marten Baudou', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('225477898-6', 'cursus id', 'Diahann Georgius', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('323700548-7', 'amet lobortis', 'Clarinda Louisot', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('472608479-8', 'vestibulum rutrum rutrum neque aenean auctor', 'Daron Lamyman', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('357411126-6', 'massa id lobortis convallis', 'Nona Mead', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('688842919-9', 'quisque porta volutpat', 'Ardra Hawksley', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('996384387-5', 'at nunc', 'Connie Challener', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('295747894-3', 'convallis nulla neque libero convallis eget', 'Jerrilee Harrowell', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('781386354-2', 'mauris viverra', 'Gnni Barefoot', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('800984509-4', 'in faucibus orci luctus', 'Joyous Fissenden', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('636918051-3', 'leo maecenas pulvinar lobortis est phasellus', 'Alexi Tuke', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('058132033-6', 'ante ipsum', 'Guthrie Saint', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('441612268-3', 'quis odio consequat', 'Paulie Vila', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('463617849-1', 'ante ipsum primis', 'Carolee Tattersdill', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('356372251-X', 'morbi odio odio elementum eu interdum', 'Neille Jales', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('841958936-5', 'natoque penatibus', 'Philippa Dell Casa', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('071065966-0', 'sit amet eleifend', 'Aguistin Goskar', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('571442045-4', 'justo eu massa donec dapibus', 'Rhiamon Yellep', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('872525751-X', 'ultrices libero non mattis pulvinar nulla', 'Griswold Townrow', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('301822883-9', 'praesent blandit', 'Delmor MacBrearty', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('497180905-8', 'ligula sit', 'Devin Jakubowicz', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('478062273-5', 'pharetra magna vestibulum aliquet', 'Inness McLeoid', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('364585155-0', 'luctus cum sociis', 'Brandais Dono', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('454978514-4', 'turpis eget elit', 'Whitney Maciejak', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('537594403-0', 'at diam nam', 'Gusti Snazle', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('699977024-7', 'primis in faucibus orci luctus et', 'Quentin Veighey', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('849268421-6', 'in faucibus orci luctus et', 'Stanfield Capey', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('714477138-8', 'ultricies eu', 'Helenka Guess', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('494838269-8', 'varius ut blandit', 'Gypsy Dibdall', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('118312091-5', 'nisi vulputate nonummy maecenas tincidunt lacus', 'Kirby Bugbird', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('516542063-9', 'posuere nonummy', 'Jud Duck', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('512198194-5', 'nulla pede', 'Thedrick Sabie', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('665918403-1', 'faucibus orci luctus et', 'Davidde Drohan', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('684969956-3', 'tristique est et tempus semper est', 'Sandy Wanklin', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('463955592-X', 'in quam', 'Igor Silman', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('588433298-X', 'in ante vestibulum ante', 'Rodrigo Dilkes', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('741270392-7', 'a odio', 'Arlee Godfree', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('710193450-1', 'nisl venenatis lacinia aenean sit', 'Diann Linton', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('106791506-0', 'mauris laoreet', 'Vi Drance', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('375219629-7', 'in libero ut', 'Bruis Heggison', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('000678085-7', 'et ultrices posuere', 'Bobina O''Grady', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('989707990-4', 'a nibh in', 'Merell Roulston', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('613127455-X', 'nisi eu orci mauris lacinia', 'Esmeralda Maior', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('356544367-7', 'quis justo maecenas rhoncus aliquam', 'Haley Josifovic', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('996551421-6', 'ipsum primis', 'Tomi Huckfield', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('050606718-1', 'et magnis dis parturient montes', 'Serge Divall', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('901390650-8', 'interdum mauris non ligula pellentesque', 'Cathlene Sprott', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('921211279-X', 'venenatis turpis enim', 'Nevil Dowsing', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('697643055-5', 'sed ante vivamus tortor duis', 'Hubie Willerstone', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('286410141-6', 'justo maecenas rhoncus aliquam lacus morbi', 'Jeanie Luten', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('326508950-9', 'morbi ut odio cras mi', 'Jasmine Prendergrass', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('537464969-8', 'vivamus tortor duis mattis', 'Hieronymus Beiderbecke', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('074686908-8', 'magna ac consequat metus sapien ut', 'Arlen de Cullip', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('868674367-6', 'sem fusce consequat nulla', 'Robinetta McHale', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('564572690-1', 'in blandit', 'Kit Tolson', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('116705209-9', 'diam neque vestibulum', 'Kristien Wannop', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('033592943-5', 'cras pellentesque volutpat dui maecenas tristique', 'Gardie Jeenes', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('118093464-4', 'proin interdum mauris non ligula pellentesque', 'Fredric Kubicki', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('071466377-8', 'ligula sit amet eleifend', 'Darb Eddisford', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('427307008-1', 'mattis odio donec vitae', 'Sharl Flippen', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('585804442-5', 'pellentesque ultrices', 'Mallory Schellig', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('655131176-8', 'penatibus et magnis dis parturient montes', 'Rozelle Polle', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('827137101-0', 'tempus semper', 'Donny Shenfish', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('099704722-4', 'ultrices posuere cubilia curae donec pharetra', 'Kira Lewry', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('787406490-9', 'elementum pellentesque', 'Franny Auguste', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('236298208-4', 'sed justo pellentesque viverra pede ac', 'Billy Oret', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('722132655-X', 'justo morbi ut odio cras', 'Ruddy Keysel', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('106338896-1', 'felis eu', 'Austen Cardillo', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('330914666-9', 'ut odio', 'Dieter Essame', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('680344297-7', 'duis aliquam convallis nunc proin', 'Nadeen Blumer', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('062094301-7', 'lectus in quam fringilla', 'Justen Chisolm', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('070529735-7', 'pellentesque ultrices', 'Ambrosius O''Roan', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('385599969-4', 'nulla tellus in sagittis dui', 'Bathsheba Toffaloni', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('458656542-X', 'erat quisque erat eros', 'Bradley Sawl', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('931667605-3', 'ac nibh fusce', 'Gypsy Riccardini', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('022123095-5', 'non quam nec dui luctus rutrum', 'Kiel Angier', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('170644450-8', 'pulvinar nulla', 'Jojo Gartery', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('347532710-4', 'est risus auctor sed', 'Joyan Goncalo', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('867640626-X', 'magna at', 'Siusan Grancher', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('971701592-9', 'pede ac diam cras', 'Vinny Duffitt', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('946048011-X', 'magna ac consequat metus', 'Hephzibah Everal', 'Economía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('768847294-6', 'ante vivamus tortor', 'Liane Poulsom', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('084431713-6', 'vestibulum ante ipsum primis', 'Kristopher Shawl', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('785258468-3', 'pulvinar lobortis', 'Hadrian Humpatch', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('226388738-5', 'quis turpis sed ante', 'Marleah Erbain', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('415497143-3', 'habitasse platea dictumst etiam faucibus', 'Taddeo Jovic', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('889850998-7', 'ac nibh fusce lacus', 'Leslie Logan', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('333637074-4', 'at velit vivamus', 'Etti Warbeys', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('319752128-5', 'sapien cum', 'Myra Kundert', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('322803845-9', 'potenti in eleifend', 'Klemens Hadley', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('054181362-5', 'iaculis diam erat fermentum justo', 'Chase O''Concannon', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('577855890-2', 'vestibulum velit id pretium', 'Robyn Manderson', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('057559115-3', 'fusce lacus purus aliquet at', 'Inger Bracer', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('182965272-9', 'magna ac consequat', 'Diane Veracruysse', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('623236194-6', 'quam sapien varius', 'Roseanna Halston', 'Terror');
