insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('312848666-2', 'sit amet justo morbi ut', 'Mellie Defraine', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('365090789-5', 'pharetra magna', 'Pattin Kornacki', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('045817634-6', 'ultrices posuere cubilia curae duis', 'Star Kalewe', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('929159696-5', 'enim lorem ipsum', 'Baxy Smithin', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('662227673-0', 'aliquet maecenas leo odio', 'Shirl Naris', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('935691282-3', 'eleifend luctus ultricies eu nibh', 'Wendeline Lamborne', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('030218894-0', 'auctor sed', 'Minta Pernell', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('589363794-1', 'ac nulla sed vel enim', 'Jorge Semeniuk', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('189752484-6', 'cubilia curae duis', 'Tarra Stooke', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('866449804-0', 'hac habitasse', 'Austina Loton', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('647645390-4', 'justo sollicitudin ut suscipit a', 'Quent Sunnucks', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('361487241-6', 'justo sit amet sapien', 'Carmen Geke', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('642479674-6', 'integer ac leo', 'Giselle Gilcrist', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('249423219-8', 'nam ultrices libero non', 'Kelli Beddis', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('295692136-3', 'aliquam sit amet diam in', 'Georgine Prickett', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('514267630-0', 'convallis duis consequat dui', 'Aguste Skaid', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('101299368-X', 'suspendisse ornare', 'Glennis McJerrow', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('567244225-0', 'augue vestibulum ante ipsum primis', 'Guthry Montez', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('301964174-8', 'donec dapibus', 'Mersey Rainsden', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('995475473-3', 'lacinia nisi venenatis', 'Derwin Trubshaw', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('865875436-7', 'in consequat', 'Kippy Lundie', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('964118877-1', 'rhoncus dui vel sem sed', 'Joshuah Burberry', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('187608855-9', 'sit amet consectetuer adipiscing elit', 'Matteo Whysall', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('759537208-9', 'justo sit amet sapien dignissim', 'Moyna Wandtke', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('368483400-9', 'integer pede justo lacinia', 'Ludwig Guthrie', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('233982471-0', 'nibh quisque id justo sit', 'Jobey Yersin', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('113725595-1', 'curae donec', 'Daffy Johncey', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('582078537-1', 'ante vivamus tortor duis mattis', 'Ginger Elacoate', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('468220007-0', 'condimentum neque', 'Killy Lund', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('652270058-1', 'at nunc commodo placerat', 'Torrance Trevan', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('967671252-3', 'sed ante', 'Kaila Morgans', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('270831368-1', 'in leo maecenas pulvinar', null, 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('739145756-6', 'potenti cras', 'Georgie Bene', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('818285970-0', 'in eleifend', 'El Dresser', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('465115357-7', 'sed tincidunt eu felis fusce', 'Wynny Wingatt', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('933409147-9', 'ligula suspendisse ornare', 'Deanna Annatt', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('087391504-6', 'vulputate elementum nullam varius nulla', 'Garek Kilgallon', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('852322767-9', 'parturient montes nascetur ridiculus', 'Cornell Stife', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('917337969-7', 'amet sem fusce consequat', 'Marven Casier', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('728935025-1', 'donec semper sapien a', 'Jenelle Oldacre', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('865701339-8', 'rutrum ac lobortis vel', 'Maggie Rimmer', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('941496880-6', 'vel sem sed sagittis nam', 'Karina Shear', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('518722584-7', 'justo in', 'Gabriellia Gooder', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('484845861-7', 'cursus id turpis integer aliquet', 'Sybyl Burnel', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('830291489-4', 'proin eu mi', 'Maure Pirson', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('620768680-2', 'convallis nulla', 'Sally Scolts', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('638000748-2', 'blandit nam', 'Amandie Mary', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('359891512-8', 'elementum pellentesque quisque porta', 'Piotr Thyng', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('313346073-0', 'augue aliquam', 'Ianthe Rule', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('682862875-6', 'maecenas ut massa', 'Melicent Janecki', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('527460191-X', 'est phasellus sit', 'Alma Davis', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('595200861-5', 'maecenas rhoncus', 'Vinson Callingham', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('840491033-2', 'ipsum primis in', 'Garrek Behrend', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('296777609-2', 'nec sem duis aliquam', 'Chickie Pimbley', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('383293643-2', 'in leo', 'Tiphani Pumphreys', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('211184751-8', 'platea dictumst', 'Kylynn Scotchmoor', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('191812582-1', 'bibendum imperdiet nullam orci pede', 'Coralie Lisamore', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('236052722-3', 'nisi nam', 'Eric Dootson', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('731391223-4', 'posuere nonummy integer', 'Eachelle Nowell', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('160021669-2', 'pede justo eu massa', 'Courtnay Lait', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('475926449-3', 'id massa id nisl', 'Lorita Cottingham', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('495766525-7', 'tristique fusce congue', 'Rocky Blondell', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('493507230-X', 'libero ut massa volutpat', 'Rosetta Glenwright', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('140422651-6', 'lacus morbi sem mauris laoreet', 'Deb Coutthart', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('563036519-3', 'turpis adipiscing lorem', 'Christi Cockett', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('014765086-0', 'purus sit', 'Kelcey Peart', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('539548682-8', 'sit amet turpis elementum', 'Daryle Troctor', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('278917098-3', 'sit amet justo morbi', 'Bettina D''Onise', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('162632066-7', 'fusce posuere felis sed lacus', 'Daisie Gowan', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('790617285-X', 'ipsum aliquam non', 'Georgianne Ablett', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('187410586-3', 'ultrices phasellus id sapien', 'Massimo Ravenscroft', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('420998978-9', 'augue vestibulum rutrum rutrum neque', 'Fey Sussems', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('262589353-2', 'a nibh in quis', 'Jackie Cattlemull', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('191349032-7', 'vitae consectetuer', 'Ivory Brogioni', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('561758644-0', 'semper porta volutpat quam', 'Merrielle Blockwell', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('622187874-8', 'eu nibh quisque id', 'Binnie Evanson', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('975869484-7', 'interdum mauris', 'Vladamir Broadist', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('495022568-5', 'quam a odio in', 'Katya Prando', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('786911970-9', 'convallis morbi', 'Eva Castagnone', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('875779303-4', 'nulla ut erat', 'Nickolas Matessian', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('028977094-7', 'quis justo maecenas rhoncus', 'Kylen Steedman', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('696853591-2', 'porttitor pede justo eu', 'Sherlock Enocksson', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('882674933-7', 'erat curabitur gravida', 'Almire Izchaki', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('024549336-0', 'mauris enim leo rhoncus', 'Colette Starkie', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('304610458-8', 'turpis elementum ligula vehicula consequat', 'Happy Caller', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('968846721-9', 'nulla elit ac nulla sed', 'Maxy Valler', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('191515795-1', 'vestibulum velit', 'Tally Langmead', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('701484248-X', 'interdum mauris', 'Davita Barles', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('953623058-5', 'ut tellus nulla ut', 'Janna Poole', 'SciFi');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('220879433-8', 'ut tellus nulla ut', 'Say Enderson', 'Ciencia');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('246169310-2', 'orci vehicula', 'Arman Pallis', 'Filosofía');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('066561248-6', 'odio elementum eu interdum eu', 'Alana Grantham', 'Política');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('434118827-5', 'rutrum nulla tellus in', 'Minda Petticrew', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('329750346-7', 'augue a', 'Pascale Lubman', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('460195765-6', 'pede lobortis ligula sit amet', 'Devi Cardozo', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('596236935-1', 'lobortis ligula', 'Garnette Sorbey', 'Drama');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('308493947-0', 'morbi ut odio cras', 'Norby Criag', 'Terror');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('257041414-X', 'volutpat convallis morbi', 'Sibylle Casetti', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('139440819-6', 'pede justo', 'Issi Jeandin', 'Cocina');
insert into libros (ISBN, TITULO, AUTORES, TEMATICAS) values ('088670167-8', 'nullam varius', 'Land Darinton', 'SciFi');
